/**
 * Persistence boundary — the ONLY module that knows how rows reach the database.
 *
 * Two modes:
 *   "db"  (default) direct idempotent upserts via the service-role key. Used
 *         for the full whitelist, where hand-pasting SQL is not reasonable.
 *   "sql" (fallback) emits numbered chunk files to paste into the Supabase SQL
 *         editor. Needs no key at all, so the whole pipeline can be exercised
 *         and reviewed without the key existing anywhere.
 *
 * Row shapes are shared by both modes and are built by pure functions, so the
 * mapping is unit-testable even though the network write is not.
 */

export type InstrumentRow = {
  title: string;
  type: "act" | "si";
  jurisdiction: string;
  legGovRef: string;
  sourceUrl: string;
  upToDateTo: string | null;
};

export type ProvisionRow = {
  legGovRef: string;
  ref: string;
  number: string | null;
  heading: string | null;
  content: string;
  versionDate: string | null;
  inForce: boolean;
  status: string | null;
  extent: string | null;
  contentOmitted: boolean;
  hasUnappliedAmendments: boolean;
  amendmentNote: string | null;
  sourceUrl: string;
  position: number;
};

export type SqlChunk = { filename: string; sql: string };

function sql(value: string | null): string {
  if (value === null || value === undefined) return "null";
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlBool(value: boolean): string {
  return value ? "true" : "false";
}

function sqlDate(value: string | null): string {
  if (!value) return "null";
  return /^\d{4}-\d{2}-\d{2}$/.test(value) ? `'${value}'::date` : "null";
}

const HEADER = [
  "-- Generated by scripts/ingest-legislation.ts — do not edit by hand.",
  "-- Source: legislation.gov.uk (Open Government Licence v3.0).",
  "-- Currency values are captured verbatim; no amendments are applied.",
  "--",
  "-- Prerequisites, in order:",
  "--   supabase/trackb1_legal_instruments_provisions.sql",
  "--   supabase/trackb2_provision_status.sql",
  "-- Safe to re-run: every statement upserts.",
];

function instrumentStatements(instruments: InstrumentRow[]): string[] {
  const lines: string[] = [];
  for (const inst of instruments) {
    lines.push(`-- ${inst.title} (${inst.legGovRef})`);
    lines.push("insert into public.legal_instruments");
    lines.push("  (title, type, jurisdiction, leg_gov_ref, source_url, up_to_date_to, last_synced)");
    lines.push("values");
    lines.push(
      `  (${sql(inst.title)}, ${sql(inst.type)}, ${sql(inst.jurisdiction)}, ` +
        `${sql(inst.legGovRef)}, ${sql(inst.sourceUrl)}, ${sqlDate(inst.upToDateTo)}, now())`
    );
    lines.push("on conflict (leg_gov_ref) do update set");
    lines.push("  title = excluded.title,");
    lines.push("  type = excluded.type,");
    lines.push("  jurisdiction = excluded.jurisdiction,");
    lines.push("  source_url = excluded.source_url,");
    lines.push("  up_to_date_to = excluded.up_to_date_to,");
    lines.push("  last_synced = excluded.last_synced,");
    lines.push("  updated_at = now();");
    lines.push("");
  }
  return lines;
}

function provisionStatement(p: ProvisionRow): string[] {
  const flags = [
    p.hasUnappliedAmendments ? "unapplied amendments" : null,
    p.status ? `status=${p.status}` : null,
    p.extent && p.extent !== "E+W" ? `extent=${p.extent}` : null,
    p.contentOmitted ? "content omitted (no operative text)" : null,
  ].filter(Boolean);

  return [
    `-- ${p.legGovRef} ${p.ref}${flags.length ? `  [${flags.join(", ")}]` : ""}`,
    "insert into public.legal_provisions",
    "  (instrument_id, ref, number, heading, content, version_date, in_force, status,",
    "   extent, content_omitted, has_unapplied_amendments, amendment_note, source_url, position)",
    "select",
    `  i.id, ${sql(p.ref)}, ${sql(p.number)}, ${sql(p.heading)},`,
    `  ${sql(p.content)},`,
    `  ${sqlDate(p.versionDate)}, ${sqlBool(p.inForce)}, ${sql(p.status)},`,
    `  ${sql(p.extent)},`,
    `  ${sqlBool(p.contentOmitted)}, ${sqlBool(p.hasUnappliedAmendments)}, ${sql(p.amendmentNote)},`,
    `  ${sql(p.sourceUrl)}, ${p.position}`,
    "from public.legal_instruments i",
    `where i.leg_gov_ref = ${sql(p.legGovRef)}`,
    "on conflict (instrument_id, ref) do update set",
    "  number = excluded.number,",
    "  heading = excluded.heading,",
    "  content = excluded.content,",
    "  version_date = excluded.version_date,",
    "  in_force = excluded.in_force,",
    "  status = excluded.status,",
    "  extent = excluded.extent,",
    "  content_omitted = excluded.content_omitted,",
    "  has_unapplied_amendments = excluded.has_unapplied_amendments,",
    "  amendment_note = excluded.amendment_note,",
    "  source_url = excluded.source_url,",
    "  position = excluded.position,",
    "  updated_at = now();",
    "",
  ];
}

const VERIFICATION_QUERY = [
  "-- Verification — the currency states should be visible here:",
  "--   ukpga/1989/41 section/8  -> has_unapplied_amendments = true, note populated",
  "--   ukpga/1989/41 section/1  -> false, 'No outstanding effects.'",
  "--   ukpga/1973/18 section/25 -> false, 'No outstanding effects.'",
  "--   29 Children Act provisions -> status = 'Repealed', in_force = false",
  "--   18 provisions -> content_omitted = true, in_force = false, status null",
  "--      (repealed but unmarked in CLML, e.g. Children Act s.54)",
  "--",
  "-- select i.leg_gov_ref, i.up_to_date_to, p.ref, p.version_date,",
  "--        p.in_force, p.status, p.content_omitted, p.has_unapplied_amendments,",
  "--        left(p.amendment_note, 100) as note",
  "-- from public.legal_provisions p",
  "-- join public.legal_instruments i on i.id = p.instrument_id",
  "-- order by i.leg_gov_ref, p.position;",
  "--",
  "-- Nothing should be in force with no text:",
  "-- select count(*) from public.legal_provisions",
  "-- where content_omitted and in_force;   -- expect 0",
  "--",
  "-- Row counts:",
  "-- select i.leg_gov_ref, count(*) filter (where p.ref like 'section%') as sections,",
  "--        count(*) filter (where p.ref like 'schedule%') as schedule_paras,",
  "--        count(*) as total",
  "-- from public.legal_provisions p",
  "-- join public.legal_instruments i on i.id = p.instrument_id",
  "-- group by i.leg_gov_ref;",
];

/**
 * Splits output into numbered files: 00 holds the instruments and the run
 * order, then one file per chunk of provisions. Each file is a self-contained
 * idempotent transaction, so any chunk can be re-run independently.
 */
export function buildSqlChunks(
  instruments: InstrumentRow[],
  provisions: ProvisionRow[],
  stamp: string,
  chunkSize: number
): SqlChunk[] {
  const chunks: SqlChunk[] = [];
  const totalChunks = Math.max(1, Math.ceil(provisions.length / chunkSize));
  const name = (index: number, label: string) =>
    `ingest-${stamp}-${String(index).padStart(2, "0")}-${label}.sql`;

  // File 00 — instruments plus the run-order manifest.
  const manifest: string[] = [
    ...HEADER,
    "--",
    `-- Generated: ${new Date().toISOString()}`,
    `-- ${instruments.length} instrument(s), ${provisions.length} provision(s).`,
    "--",
    "-- RUN THESE FILES IN ORDER:",
    `--   ${name(0, "instruments")}   (this file)`,
  ];
  for (let i = 0; i < totalChunks; i++) {
    manifest.push(`--   ${name(i + 1, "provisions")}`);
  }
  manifest.push("", "begin;", "", ...instrumentStatements(instruments), "commit;", "");
  chunks.push({ filename: name(0, "instruments"), sql: manifest.join("\n") });

  // Provision chunks.
  for (let i = 0; i < totalChunks; i++) {
    const slice = provisions.slice(i * chunkSize, (i + 1) * chunkSize);
    const lines: string[] = [
      ...HEADER,
      "--",
      `-- Provisions ${i * chunkSize + 1}–${i * chunkSize + slice.length} of ${provisions.length}`,
      `-- Chunk ${i + 1} of ${totalChunks}. Requires ${name(0, "instruments")} to have run.`,
      "",
      "begin;",
      "",
    ];
    for (const provision of slice) lines.push(...provisionStatement(provision));
    lines.push("commit;", "");
    if (i === totalChunks - 1) lines.push(...VERIFICATION_QUERY, "");
    chunks.push({ filename: name(i + 1, "provisions"), sql: lines.join("\n") });
  }

  return chunks;
}

// ---------------------------------------------------------------------------
// Direct database mode
// ---------------------------------------------------------------------------

/** Column mapping for legal_instruments. Pure — unit-testable. */
export function instrumentToRecord(inst: InstrumentRow, syncedAt: string) {
  return {
    title: inst.title,
    type: inst.type,
    jurisdiction: inst.jurisdiction,
    leg_gov_ref: inst.legGovRef,
    source_url: inst.sourceUrl,
    up_to_date_to: inst.upToDateTo,
    last_synced: syncedAt,
    updated_at: syncedAt,
  };
}

/** Column mapping for legal_provisions. Pure — unit-testable. */
export function provisionToRecord(
  provision: ProvisionRow,
  instrumentId: string,
  syncedAt: string
) {
  return {
    instrument_id: instrumentId,
    ref: provision.ref,
    number: provision.number,
    heading: provision.heading,
    content: provision.content,
    version_date: provision.versionDate,
    in_force: provision.inForce,
    status: provision.status,
    extent: provision.extent,
    content_omitted: provision.contentOmitted,
    has_unapplied_amendments: provision.hasUnappliedAmendments,
    amendment_note: provision.amendmentNote,
    source_url: provision.sourceUrl,
    position: provision.position,
    updated_at: syncedAt,
  };
}

export function chunk<T>(items: T[], size: number): T[][] {
  const out: T[][] = [];
  for (let i = 0; i < items.length; i += size) out.push(items.slice(i, i + size));
  return out;
}

/** Minimal surface of the Supabase client we rely on, so tests can fake it. */
export type UpsertClient = {
  from: (table: string) => {
    upsert: (
      values: Record<string, unknown>[],
      options: { onConflict: string }
    ) => {
      select: (columns: string) => Promise<{
        data: Record<string, unknown>[] | null;
        error: { message: string } | null;
      }>;
    };
  };
};

export type DbWriteResult = {
  instrumentsWritten: number;
  provisionsWritten: number;
};

/**
 * Upserts instruments then provisions. Idempotent: conflicts update in place,
 * so a re-run after a partial failure converges rather than duplicating.
 *
 * Batches are not one transaction — an interrupted run can leave a subset
 * written. That is acceptable precisely because the operation is idempotent.
 */
export async function writeToDatabase(
  client: UpsertClient,
  instruments: InstrumentRow[],
  provisions: ProvisionRow[],
  batchSize = 500,
  onProgress?: (written: number, total: number) => void
): Promise<DbWriteResult> {
  const syncedAt = new Date().toISOString();

  const instrumentRecords = instruments.map((i) => instrumentToRecord(i, syncedAt));
  const { data: instrumentRows, error: instrumentError } = await client
    .from("legal_instruments")
    .upsert(instrumentRecords, { onConflict: "leg_gov_ref" })
    .select("id,leg_gov_ref");

  if (instrumentError) {
    throw new Error(`Instrument upsert failed: ${instrumentError.message}`);
  }

  const idByRef = new Map<string, string>();
  for (const row of instrumentRows ?? []) {
    idByRef.set(String(row.leg_gov_ref), String(row.id));
  }

  const missing = [...new Set(provisions.map((p) => p.legGovRef))].filter(
    (ref) => !idByRef.has(ref)
  );
  if (missing.length) {
    throw new Error(`No instrument id returned for: ${missing.join(", ")}`);
  }

  let provisionsWritten = 0;
  for (const batch of chunk(provisions, batchSize)) {
    const records = batch.map((p) =>
      provisionToRecord(p, idByRef.get(p.legGovRef)!, syncedAt)
    );
    const { error } = await client
      .from("legal_provisions")
      .upsert(records, { onConflict: "instrument_id,ref" })
      .select("id");
    if (error) {
      throw new Error(
        `Provision upsert failed after ${provisionsWritten} rows: ${error.message}`
      );
    }
    provisionsWritten += batch.length;
    onProgress?.(provisionsWritten, provisions.length);
  }

  return { instrumentsWritten: instrumentRecords.length, provisionsWritten };
}
