/**
 * Persistence boundary — the ONLY module that knows how rows reach the database.
 *
 * Today it emits idempotent INSERT SQL for pasting into the Supabase SQL
 * editor, so no service-role key exists anywhere. When the corpus grows past
 * hand-pasting, swap this one file for a supabase-js writer using a key held
 * only in scripts/.env (gitignored) — nothing else needs to change.
 */

export type InstrumentRow = {
  title: string;
  type: "act" | "si";
  jurisdiction: string;
  legGovRef: string;
  sourceUrl: string;
  upToDateTo: string | null;
};

export type ProvisionRow = {
  legGovRef: string;
  ref: string;
  number: string | null;
  heading: string | null;
  content: string;
  versionDate: string | null;
  inForce: boolean;
  hasUnappliedAmendments: boolean;
  amendmentNote: string | null;
  sourceUrl: string;
  position: number;
};

/** Single-quote escaping for SQL string literals. */
function sql(value: string | null): string {
  if (value === null || value === undefined) return "null";
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlBool(value: boolean): string {
  return value ? "true" : "false";
}

function sqlDate(value: string | null): string {
  if (!value) return "null";
  // Guard against anything that isn't an ISO date reaching the SQL.
  return /^\d{4}-\d{2}-\d{2}$/.test(value) ? `'${value}'::date` : "null";
}

export function buildSqlScript(
  instruments: InstrumentRow[],
  provisions: ProvisionRow[]
): string {
  const lines: string[] = [];

  lines.push("-- Generated by scripts/ingest-legislation.ts — do not edit by hand.");
  lines.push(`-- Generated: ${new Date().toISOString()}`);
  lines.push("-- Source: legislation.gov.uk (Open Government Licence v3.0).");
  lines.push("-- Currency values are captured verbatim; no amendments are applied.");
  lines.push("--");
  lines.push("-- Prerequisite: run supabase/trackb1_legal_instruments_provisions.sql first.");
  lines.push("-- Safe to re-run: every statement upserts.");
  lines.push("");
  lines.push("begin;");
  lines.push("");

  for (const inst of instruments) {
    lines.push(`-- ${inst.title} (${inst.legGovRef})`);
    lines.push("insert into public.legal_instruments");
    lines.push("  (title, type, jurisdiction, leg_gov_ref, source_url, up_to_date_to, last_synced)");
    lines.push("values");
    lines.push(
      `  (${sql(inst.title)}, ${sql(inst.type)}, ${sql(inst.jurisdiction)}, ` +
        `${sql(inst.legGovRef)}, ${sql(inst.sourceUrl)}, ${sqlDate(inst.upToDateTo)}, now())`
    );
    lines.push("on conflict (leg_gov_ref) do update set");
    lines.push("  title = excluded.title,");
    lines.push("  type = excluded.type,");
    lines.push("  jurisdiction = excluded.jurisdiction,");
    lines.push("  source_url = excluded.source_url,");
    lines.push("  up_to_date_to = excluded.up_to_date_to,");
    lines.push("  last_synced = excluded.last_synced,");
    lines.push("  updated_at = now();");
    lines.push("");
  }

  for (const p of provisions) {
    lines.push(`-- ${p.legGovRef} ${p.ref}${p.hasUnappliedAmendments ? "  [unapplied amendments]" : ""}`);
    lines.push("insert into public.legal_provisions");
    lines.push(
      "  (instrument_id, ref, number, heading, content, version_date, in_force,"
    );
    lines.push(
      "   has_unapplied_amendments, amendment_note, source_url, position)"
    );
    lines.push("select");
    lines.push(`  i.id, ${sql(p.ref)}, ${sql(p.number)}, ${sql(p.heading)},`);
    lines.push(`  ${sql(p.content)},`);
    lines.push(`  ${sqlDate(p.versionDate)}, ${sqlBool(p.inForce)},`);
    lines.push(`  ${sqlBool(p.hasUnappliedAmendments)}, ${sql(p.amendmentNote)},`);
    lines.push(`  ${sql(p.sourceUrl)}, ${p.position}`);
    lines.push("from public.legal_instruments i");
    lines.push(`where i.leg_gov_ref = ${sql(p.legGovRef)}`);
    lines.push("on conflict (instrument_id, ref) do update set");
    lines.push("  number = excluded.number,");
    lines.push("  heading = excluded.heading,");
    lines.push("  content = excluded.content,");
    lines.push("  version_date = excluded.version_date,");
    lines.push("  in_force = excluded.in_force,");
    lines.push("  has_unapplied_amendments = excluded.has_unapplied_amendments,");
    lines.push("  amendment_note = excluded.amendment_note,");
    lines.push("  source_url = excluded.source_url,");
    lines.push("  position = excluded.position,");
    lines.push("  updated_at = now();");
    lines.push("");
  }

  lines.push("commit;");
  lines.push("");
  lines.push("-- Verification: the s.8 vs s.25 currency difference should be visible here.");
  lines.push("--   ukpga/1989/41 section/8  -> has_unapplied_amendments = true,  amendment_note populated");
  lines.push("--   ukpga/1973/18 section/25 -> has_unapplied_amendments = false, 'No outstanding effects.'");
  lines.push("--");
  lines.push("-- select i.leg_gov_ref, i.up_to_date_to, p.ref, p.version_date, p.in_force,");
  lines.push("--        p.has_unapplied_amendments, left(p.amendment_note, 120) as note");
  lines.push("-- from public.legal_provisions p");
  lines.push("-- join public.legal_instruments i on i.id = p.instrument_id");
  lines.push("-- order by i.leg_gov_ref, p.position;");
  lines.push("");

  return lines.join("\n");
}
