/**
 * Persistence boundary — the ONLY module that knows how rows reach the database.
 *
 * Today it emits idempotent INSERT SQL for pasting into the Supabase SQL
 * editor, so no service-role key exists anywhere. At ~600 provisions the output
 * is split into numbered chunk files small enough for the editor.
 *
 * PROPOSED (not built here): at full whitelist scale (~35 instruments,
 * thousands of provisions) hand-pasting stops being reasonable. Replace this
 * module with a supabase-js writer using a service-role key held only in
 * scripts/.env (already covered by .gitignore's .env*, never in the app).
 * Nothing outside this file needs to change.
 */

export type InstrumentRow = {
  title: string;
  type: "act" | "si";
  jurisdiction: string;
  legGovRef: string;
  sourceUrl: string;
  upToDateTo: string | null;
};

export type ProvisionRow = {
  legGovRef: string;
  ref: string;
  number: string | null;
  heading: string | null;
  content: string;
  versionDate: string | null;
  inForce: boolean;
  status: string | null;
  hasUnappliedAmendments: boolean;
  amendmentNote: string | null;
  sourceUrl: string;
  position: number;
};

export type SqlChunk = { filename: string; sql: string };

function sql(value: string | null): string {
  if (value === null || value === undefined) return "null";
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlBool(value: boolean): string {
  return value ? "true" : "false";
}

function sqlDate(value: string | null): string {
  if (!value) return "null";
  return /^\d{4}-\d{2}-\d{2}$/.test(value) ? `'${value}'::date` : "null";
}

const HEADER = [
  "-- Generated by scripts/ingest-legislation.ts — do not edit by hand.",
  "-- Source: legislation.gov.uk (Open Government Licence v3.0).",
  "-- Currency values are captured verbatim; no amendments are applied.",
  "--",
  "-- Prerequisites, in order:",
  "--   supabase/trackb1_legal_instruments_provisions.sql",
  "--   supabase/trackb2_provision_status.sql",
  "-- Safe to re-run: every statement upserts.",
];

function instrumentStatements(instruments: InstrumentRow[]): string[] {
  const lines: string[] = [];
  for (const inst of instruments) {
    lines.push(`-- ${inst.title} (${inst.legGovRef})`);
    lines.push("insert into public.legal_instruments");
    lines.push("  (title, type, jurisdiction, leg_gov_ref, source_url, up_to_date_to, last_synced)");
    lines.push("values");
    lines.push(
      `  (${sql(inst.title)}, ${sql(inst.type)}, ${sql(inst.jurisdiction)}, ` +
        `${sql(inst.legGovRef)}, ${sql(inst.sourceUrl)}, ${sqlDate(inst.upToDateTo)}, now())`
    );
    lines.push("on conflict (leg_gov_ref) do update set");
    lines.push("  title = excluded.title,");
    lines.push("  type = excluded.type,");
    lines.push("  jurisdiction = excluded.jurisdiction,");
    lines.push("  source_url = excluded.source_url,");
    lines.push("  up_to_date_to = excluded.up_to_date_to,");
    lines.push("  last_synced = excluded.last_synced,");
    lines.push("  updated_at = now();");
    lines.push("");
  }
  return lines;
}

function provisionStatement(p: ProvisionRow): string[] {
  const flags = [
    p.hasUnappliedAmendments ? "unapplied amendments" : null,
    p.status ? `status=${p.status}` : null,
  ].filter(Boolean);

  return [
    `-- ${p.legGovRef} ${p.ref}${flags.length ? `  [${flags.join(", ")}]` : ""}`,
    "insert into public.legal_provisions",
    "  (instrument_id, ref, number, heading, content, version_date, in_force, status,",
    "   has_unapplied_amendments, amendment_note, source_url, position)",
    "select",
    `  i.id, ${sql(p.ref)}, ${sql(p.number)}, ${sql(p.heading)},`,
    `  ${sql(p.content)},`,
    `  ${sqlDate(p.versionDate)}, ${sqlBool(p.inForce)}, ${sql(p.status)},`,
    `  ${sqlBool(p.hasUnappliedAmendments)}, ${sql(p.amendmentNote)},`,
    `  ${sql(p.sourceUrl)}, ${p.position}`,
    "from public.legal_instruments i",
    `where i.leg_gov_ref = ${sql(p.legGovRef)}`,
    "on conflict (instrument_id, ref) do update set",
    "  number = excluded.number,",
    "  heading = excluded.heading,",
    "  content = excluded.content,",
    "  version_date = excluded.version_date,",
    "  in_force = excluded.in_force,",
    "  status = excluded.status,",
    "  has_unapplied_amendments = excluded.has_unapplied_amendments,",
    "  amendment_note = excluded.amendment_note,",
    "  source_url = excluded.source_url,",
    "  position = excluded.position,",
    "  updated_at = now();",
    "",
  ];
}

const VERIFICATION_QUERY = [
  "-- Verification — the currency states should be visible here:",
  "--   ukpga/1989/41 section/8  -> has_unapplied_amendments = true, note populated",
  "--   ukpga/1989/41 section/1  -> false, 'No outstanding effects.'",
  "--   ukpga/1973/18 section/25 -> false, 'No outstanding effects.'",
  "--   29 Children Act provisions -> status = 'Repealed', in_force = false",
  "--",
  "-- select i.leg_gov_ref, i.up_to_date_to, p.ref, p.version_date,",
  "--        p.in_force, p.status, p.has_unapplied_amendments,",
  "--        left(p.amendment_note, 100) as note",
  "-- from public.legal_provisions p",
  "-- join public.legal_instruments i on i.id = p.instrument_id",
  "-- order by i.leg_gov_ref, p.position;",
  "--",
  "-- Row counts:",
  "-- select i.leg_gov_ref, count(*) filter (where p.ref like 'section%') as sections,",
  "--        count(*) filter (where p.ref like 'schedule%') as schedule_paras,",
  "--        count(*) as total",
  "-- from public.legal_provisions p",
  "-- join public.legal_instruments i on i.id = p.instrument_id",
  "-- group by i.leg_gov_ref;",
];

/**
 * Splits output into numbered files: 00 holds the instruments and the run
 * order, then one file per chunk of provisions. Each file is a self-contained
 * idempotent transaction, so any chunk can be re-run independently.
 */
export function buildSqlChunks(
  instruments: InstrumentRow[],
  provisions: ProvisionRow[],
  stamp: string,
  chunkSize: number
): SqlChunk[] {
  const chunks: SqlChunk[] = [];
  const totalChunks = Math.max(1, Math.ceil(provisions.length / chunkSize));
  const name = (index: number, label: string) =>
    `ingest-${stamp}-${String(index).padStart(2, "0")}-${label}.sql`;

  // File 00 — instruments plus the run-order manifest.
  const manifest: string[] = [
    ...HEADER,
    "--",
    `-- Generated: ${new Date().toISOString()}`,
    `-- ${instruments.length} instrument(s), ${provisions.length} provision(s).`,
    "--",
    "-- RUN THESE FILES IN ORDER:",
    `--   ${name(0, "instruments")}   (this file)`,
  ];
  for (let i = 0; i < totalChunks; i++) {
    manifest.push(`--   ${name(i + 1, "provisions")}`);
  }
  manifest.push("", "begin;", "", ...instrumentStatements(instruments), "commit;", "");
  chunks.push({ filename: name(0, "instruments"), sql: manifest.join("\n") });

  // Provision chunks.
  for (let i = 0; i < totalChunks; i++) {
    const slice = provisions.slice(i * chunkSize, (i + 1) * chunkSize);
    const lines: string[] = [
      ...HEADER,
      "--",
      `-- Provisions ${i * chunkSize + 1}–${i * chunkSize + slice.length} of ${provisions.length}`,
      `-- Chunk ${i + 1} of ${totalChunks}. Requires ${name(0, "instruments")} to have run.`,
      "",
      "begin;",
      "",
    ];
    for (const provision of slice) lines.push(...provisionStatement(provision));
    lines.push("commit;", "");
    if (i === totalChunks - 1) lines.push(...VERIFICATION_QUERY, "");
    chunks.push({ filename: name(i + 1, "provisions"), sql: lines.join("\n") });
  }

  return chunks;
}
